### ISSUE TITLE
Drone Gripper Mechanism

### ISSUE THREAD

**Issue by adamhamdan8** [uf-mil-mechanical/tasks#5]
The autonomous drone on NaviGator is required to pick up a tin can, move with it gripped, and drop it at another location. To do this, we need to create a mechanism capable of holding the tin can. Good thing is that the can is magnetic!

Task Requirements:
- Needs to be able to hold onto and release the tin can with stability
- Needs to minimize current pull from drone (or use separate battery) 
- Needs to be as easy as possible for the drone to pick up the can (minimize clearance and accuracy needed)

Preliminary Ideas:
- A magnet that can pick up the tin can as the drone approaches it, with a solenoid that "releases" the magnet
- An electromagnet that we can turn on or off
- A magnet that can pick up the tin can, with some sort of 3D printed part + servo combo to push the can away from the magnet

**Comment by adamhamdan8** [comment]
@FindlayWatson @joshvale227 We can make the arm that holds the mechanism telescopic, which should make it a lot easier to land the drone on a flat surface. Idea from Lester that I think is great we gotta do that. This means that the landing pad is easier to design as well. No hole or anything

**Comment by adamhamdan8** [comment]
@joshvale227 @FindlayWatson Can one of you two also spray paint our tin cans by this sunday for our CV model. We have tons of them and we should have spray paint, if not I can buy you guys some. Let me know please!

**Comment by joshvale227** [comment]
> @joshvale227 @FindlayWatson Can one of you two also spray paint our tin cans by this sunday for our CV model. We have tons of them and we should have spray paint, if not I can buy you guys some. Let me know please!

Sure, I'll be doing that right now. Found some spray paint for the colors we need. Edit: unsure where the tin cans are now, apparently they are being used to store stuff but unsure as to whether they are the same ones as the ones we need for the task

**Comment by FindlayWatson** [comment]
> @FindlayWatson @joshvale227 We can make the arm that holds the mechanism telescopic, which should make it a lot easier to land the drone on a flat surface. Idea from Lester that I think is great we gotta do that. This means that the landing pad is easier to design as well. No hole or anything

Having a telescopic arm seems far more complicated and has the possibility of breaking or jamming mid competition.

I talked with Gabe and there seemes to be absolutly no issue with cutting a hole through the center of the landing pad. Allowing us to have the magnet and mechanism hang below the drone. 

If having the magnet hanging below the legs of the drone is that big of an issue when it comes to designing a landing pad then we should move back to using a solenoid. The problem with the solenoids we puchased is that the traveling distance on them is far too short to reliably pickup and then drop the tins using a magnet. i.e. the 1cm travel of our solenoids still attract the tin to our magnet. I am currently designing an attachment to hopefully find the happy medium where the magnet will want to drop the tin when activated and pick it up when not. However, having this 1cm travel distance then gives very little clearence between the bottom of the drone legs and the magnet. I am not certain but this could very possibly risk the legs of the drone running into the tin when attempting pickup.

When looking for solenoids this past week the travel distance was my major concern. I did find [this](https://www.amazon.com/Abletop-Solenoid-Electromagnetic-Electric-Automobiles/dp/B07G15X91N) solenoid on amazon with a 3.5cm tavel distance, which I have no doubt would solve many of our issues our current solenoids propose.

**Comment by adamhamdan8** [comment]
> > @joshvale227 @FindlayWatson Can one of you two also spray paint our tin cans by this sunday for our CV model. We have tons of them and we should have spray paint, if not I can buy you guys some. Let me know please!
> 
> Sure, I'll be doing that right now. Found some spray paint for the colors we need. Edit: unsure where the tin cans are now, apparently they are being used to store stuff but unsure as to whether they are the same ones as the ones we need for the task

I believe they are in cabinet 100 in a giant tupperware. They are just small metal tins, if you need to empty the stuff in them, do so and just let us know where you put the stuff. See the handbook if you need to confirm the tins are the correct ones
Edit: Just saw that you did them thank you!!

**Comment by FindlayWatson** [comment]
Weekly Report:

I finished and printed a my first design for the telescoping arm. I will get around to posting photos and such tomorrow. I have a concern which I brought up previously about the arm jamming and will research ways around said problem.

I also redesigned the CAD for the magnetic mechanism as the CAD for the design we have now is lost. I trimmed down the size of the whole mechanism to aide in the necessary travel distance of the telescoping arm.

**Comment by joshvale227** [comment]
Judging from the STP file Lester sent in mech. general, there is around 220.4 mm (~8.677 in) of room for a solenoid to fit within the room of the legs. It also affects the drone's landing pad, with how deep the center hole would be (along with anything else to push the can off the solenoid). With the solenoid in mind, there would be around 121 mm (~4.764 in) left between the end of the solenoid fully extended and the bottom of the drone’s legs. Even with some extension and bracket to support the solenoid onto the drone, we would need a decently powerful magnet to attract the tin can (say an inch or 2). The only major issue with having a solenoid like this is that it cannot be left on for too long or else it will overheat. This amount of time must be more than when the drone finds the next pad to drop the tin can. Once we have the solenoid, measurements can be made to accurately measure the holes on the side shown to create an enclosure that can hold the solenoid to the drone while also having a hole so that once the solenoid is retracted, the can falls off. EDIT: after reading Finn’s report, I want to see more on this telescoping arm stuff before making something for housing the solenoid (if this is the solenoid we end up using) or just go with the stuff Lorant previously had. 

![Picture1](https://github.com/user-attachments/assets/2b49c9b2-0c2c-4089-a7d9-2744e4e74d04)
![Picture2](https://github.com/user-attachments/assets/de0e0099-9f1e-4877-9c17-81b7e0561373)

**Comment by adamhamdan8** [comment]
> Weekly Report:
> 
> I finished and printed a my first design for the telescoping arm. I will get around to posting photos and such tomorrow. I have a concern which I brought up previously about the arm jamming and will research ways around said problem.
> 
> I also redesigned the CAD for the magnetic mechanism as the CAD for the design we have now is lost. I trimmed down the size of the whole mechanism to aide in the necessary travel distance of the telescoping arm.

Hey Finn, thanks for the work. Next time try and include images, file names, etc for the work that you did so things are documented in one place.

**Comment by adamhamdan8** [comment]
@FindlayWatson and @joshvale227 How did the telescoping alternatives go? And how is the servo and mechanism replacement? We want to try and get this done for next week!

**Comment by joshvale227** [comment]
Sorry for not responding earlier, I have been sick since Friday but went to the lab that day to take more accurate measurements because the first time I did it, the dimensions seemed sus. I am feeling a little better now so trying to cad up a support for the servo to be attached to the drone using the file on hand and an attachment for the servo to increase the length of travel. Gonna finish the supports by today to be printed tomorrow. Only issue though is that the longer the attachment, the more likely it will be to wobble (will see if there is anything else that can be done). 

![drawings for servo travel of 1](https://github.com/user-attachments/assets/a561efe0-d940-4a20-aec4-00f7d5322be8)

**Comment by FindlayWatson** [comment]
> [@FindlayWatson](https://github.com/FindlayWatson) and [@joshvale227](https://github.com/joshvale227) How did the telescoping alternatives go? And how is the servo and mechanism replacement? We want to try and get this done for next week

We are looking good. I have it printed so we can take a look at it Tuesday.

**Comment by FindlayWatson** [comment]
I modeled the drone magnetic dropper and made a folder for it in fusion, titled 'Drone Dropper'. 
![Image](https://github.com/user-attachments/assets/a24130fe-98a2-4252-b089-66458cbafed5)

I also designed a new arm to mount the dropper to. At first look this arm should work as we want with no qualms. See images below.
![Image](https://github.com/user-attachments/assets/951d1750-c60b-4dc0-b926-428788a9773d)
![Image](https://github.com/user-attachments/assets/1eaee83c-4a6c-455d-97ca-ea1190ee2b49)

**Comment by joshvale227** [comment]
![image](https://github.com/user-attachments/assets/3b5fc3ba-8ad5-4b85-b40c-47ef54dc17da)

Sort of how the enclosure would look like for solenoid if we go through that route (of course there would be a top portion securing it and also along some portion of the moving arm in future iterations) along with a support for 1/4 bolts to attach to the middle of the drone. To ensure COMPLETE contact, a 4.395" extension arm would have to be made, however due to how strong a magnet could get, realistically a 1-2" extension would have to be fitted onto the slot of the solenoid and some conical portion to cause the magnet to fall off when the solenoid is turned on, as it is normally extended. I'll send the file tomorrow for prototype print

**Comment by joshvale227** [comment]
With showcase/applications, hurricane issues around my apartment, and reviewing for exams I have this week, I haven't made any progress regarding mounts and extensions for the solenoid. Want to finish work Monday hopefully and assist with any other prop stuff.

**Comment by FindlayWatson** [comment]
> With showcase/applications, hurricane issues around my apartment, and reviewing for exams I have this week, I haven't made any progress regarding mounts and extensions for the solenoid. Want to finish work Monday hopefully and assist with any other prop stuff.

Im in the same boat. I did resize some things so that they fit aa little buit better. Other than that, Im waiting on getting the CAD file for the drone so I can make a mount. If there isnt one soon Ill end up just measuring everything with calipers.

**Comment by adamhamdan8** [comment]
Word on the street is that the drone is blowing away the tin cans. The competition people may be adding weights to the tin cans, so we will have to see how that plays out.

**Comment by FindlayWatson** [comment]
Lorant gave me a stronger magnet to use. Im confident itll work but well find out this weekend

**Comment by adamhamdan8** [comment]
> Lorant gave me a stronger magnet to use. Im confident itll work but well find out this weekend

Great! The drone is now moving so if you want to work on getting the mechanism on that would be awesome!

**Comment by FindlayWatson** [comment]
Finished Cad for Dropper Arm and Mount. Printed both using PLA, may want to upgrade to PETG. Attached to drone and ready for testing.

![Image](https://github.com/user-attachments/assets/89a292fb-4b59-4ab1-8538-bf0bdc1f89c9)

**Comment by joshvale227** [comment]
Made a separate CAD model for a base attachment for the servo as backup, need to tweak some things regarding how to mount it properly to the servo (keyed slot and a bolt or something to turn) as well as for reducing weight as right now it's just a block with some holes and and slots. Also sent something regarding the CAD t-shirt thing. 

![image](https://github.com/user-attachments/assets/7fd035e1-165c-4bf4-a0a6-6c8966d9c74f)

**Comment by joshvale227** [comment]
![image](https://github.com/user-attachments/assets/3ee20254-1b2c-4daa-9028-0b06cd1b89df)
I edited some portions of the above base for the servo and extended arm and updated the magnet mount to the servo to the new one given. I still need to figure out whether to use a slot or a bolt to secure the cylindrical arm to the servo fixture, but at this point, it's looking similar to the other design. As of right now, there is ~4.634" of separation between the maximum length of the servo and the top of the can, so that is an issue with whether the magnet can pick it up or not.

**Comment by FindlayWatson** [comment]
Attached the final mechanism this week. All I believe there is to do now is add the larger magnet. Other than that its just editing whatever issues come up.

**Comment by adamhamdan8** [comment]
Have we tested this at all to see if it works? @FindlayWatson you may need to get in contact with Lester to try and get the mechanism tested and connected on the actual drone!

**Comment by FindlayWatson** [comment]
We tested it while not connected, the mechanism worked but to be safe we have an attachment being made for the stringer magnet. I’ll let Lester know about hooking up the servo right now.

**Comment by joshvale227** [comment]
Helped clean up a bit the lab and also painted the tin cans for drone testing. Modified a bit the magnet holder for the solenoid

![image](https://github.com/user-attachments/assets/42720b8f-6d27-4e82-abe3-b4e14e940b9b)

**Comment by adamhamdan8** [comment]
> Helped clean up a bit the lab and also painted the tin cans for drone testing. Modified a bit the magnet holder for the solenoid
> 
> ![image](https://github.com/user-attachments/assets/42720b8f-6d27-4e82-abe3-b4e14e940b9b)

Are you not missing another tin?

Also @FindlayWatson and @joshvale227 is the mechanism finalized on the drone and has it been tested?

**Comment by joshvale227** [comment]
> > Helped clean up the lab a bit and also painted the tin cans for drone testing. Modified a bit the magnet holder for the solenoid
> > ![image](https://private-user-images.githubusercontent.com/45826880/378256935-42720b8f-6d27-4e82-abe3-b4e14e940b9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjAzMTIsIm5iZiI6MTcyOTg2MDAxMiwicGF0aCI6Ii80NTgyNjg4MC8zNzgyNTY5MzUtNDI3MjBiOGYtNmQyNy00ZTgyLWFiZTMtYjRlMTRlOTQwYjliLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDEyNDAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYmExMmY1ZjMyNzY3MjQ5YTY0YzJhMmQ3ZDUyMzUwY2FhMGZiNDUwZTI4Njg5MWI3MTZmYTAwZmQ1MGJlNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4DRYN0yKH0dRtAJIcF0XqIhsnLEEDlNL7oeTVNeU1LQ)
> 
> Are you not missing another tin?
> 
> Also @FindlayWatson and @joshvale227 is the mechanism finalized on the drone and has it been tested?

Yes, I was going to use it through the order form and talk to you about that, but I have been completely busy these past couple of days from being sick. I just put in the order and will go and check at the lab about the mechanism

**Comment by FindlayWatson** [comment]
> Also [@FindlayWatson](https://github.com/FindlayWatson) and [@joshvale227](https://github.com/joshvale227) is the mechanism finalized on the drone and has it been tested?

I just checked and lester never got back to me. I'll message him again and hopefully run into him when I go in Monday.

**Comment by FindlayWatson** [comment]
> > Also [@FindlayWatson](https://github.com/FindlayWatson) and [@joshvale227](https://github.com/joshvale227) is the mechanism finalized on the drone and has it been tested?
> 
> I just checked and lester never got back to me. I'll message him again and hopefully run into him when I go in Monday.

He just got back to me, hooking up and testing the servo now!

**Comment by FindlayWatson** [comment]
Just got an update on testing. Looks like the magnet works perfect, however, the arm broke because of a tough landing. Planning on reprinting in PETG and also adding a extra mount to the bottom of the legs to make the arm a bit tougher.

**Comment by adamhamdan8** [comment]
> Just got an update on testing. Looks like the magnet works perfect, however, the arm broke because of a tough landing. Planning on reprinting in PETG and also adding a extra mount to the bottom of the legs to make the arm a bit tougher.

Hey @FindlayWatson try and print an extra one or two as well in case they break at competition. Glad the mechanism works well tho! When thats done we can close the issue. Keep in mind we are leaving Saturday

**Comment by joshvale227** [comment]
I cleaned off the thruster shroud prints and ball launcher prints made during that time frame. I passed by and found an extra tin can lying around and painted it for testing later that day.

**Comment by FindlayWatson** [comment]
Past week: printed the extra parts for the arm

**Comment by adamhamdan8** [comment]
@nonagaga made a new version while at competition to handle the heavier tins. We did not attempt the task but it should be there and made! Good enough for now
