### ISSUE TITLE
[Props and Obstacles] Demonstration Gates

### ISSUE THREAD

**Issue by lorantdomokos** [uf-mil-mechanical/tasks#6]
Associated RobotX task: Dynamic Navigation Demonstration

Find/buy/build the buoys, ropes and weights for the Dynamic Navigation Demonstration. Each RobotX team has to demonstrate their navigation capabilities to qualify for the competition.

To ensure that the computer vision model can accurately recognize both our buoys and the competition buoys, make sure the following are met.
- Buoys are roughly the correct size.
- Buoys have a tall conical part and a wider bottom part.

Buoys needed:
- [ ] 2 red buoys
- [ ] 2 green buoys

![Image](https://github.com/user-attachments/assets/264b0708-9e41-4274-8d73-99ca3c0bab9f)

**Comment by adamhamdan8** [comment]
@bcobo04 and @DiegoDom23 , I accidentally assigned you guys to the wrong issue. This is the one you guys need to work on. Please shift on over here. My apologies, I will post over the spec sheet as well. We want to get this done by next weekend at the latest, try and get bom so that I can run to Lowe's and purchase stuff for you guys. We have old structures for the buoy, we just need new pool noodles and some sort of covering that we can paint red and green.

**Comment by adamhamdan8** [comment]
![image_2024-09-04_135935306](https://github.com/user-attachments/assets/294ecd9c-c703-4cc1-bf95-3965d015d489)
These are the specs from their website from Blake

**Comment by adamhamdan8** [comment]
I spoke with @DiegoDom23 and we decided on using corrugated plastic for the buoy, and he will compile a BOM for me to go purchase at Lowe's, which I will then bring back into the lab for assembly this weekend for next week.

**Comment by DiegoDom23** [comment]
Attached is the BOM to purchase at Lowe's. The only doubt is the corrugated plastic due to the price as the sheets run for expensive prices. The list contains a cardboard cylinder for the top of the buoys which can lead to problems if it gets too wet, which is why corrugated plastic would be better. If corrugated plastic is use, the top will have to be built from scratch and then painted red and green. 

I have also attached a picture of the current buoy we will be fixing. The dimensions are 29 inches by 29 inches of PVC pipe. The top post (sticking out from the 
buoy) is 39 inches. Zip ties will be used to strap the pool noodles to the pipes. 

![IMG_1054](https://github.com/user-attachments/assets/eae03906-8c69-4924-841c-813ae964a974)
[Lowes Run for Buoys.pdf](https://github.com/user-attachments/files/16913904/Lowes.Run.for.Buoys.pdf)

**Comment by adamhamdan8** [comment]
@DiegoDom23 Could you edit the bom to have the number of each item as well? Afterwards I will go buy the stuff so you can build it early next week!

**Comment by DiegoDom23** [comment]
I've updated with the number of each item, except the corrugated plastic sheets since they are expensive and I have no experience dealing with them. The ones I found at the Lowes website lack the dimension to be used for the bottom rectangular base so multiple sheets would have to be used. I am also keeping the BOM as a word document just so it is easier to edit.
[Lowes.Run.for.Buoys.docx](https://github.com/user-attachments/files/16919302/Lowes.Run.for.Buoys.docx)

**Comment by adamhamdan8** [comment]
@DiegoDom23 I found something from home depot, I'm fine with getting it from there. we can talk tomorrow but I need this put together and finalized. Trusting your judgement on this, but I can explain my ideas tomorrow before we order. https://www.homedepot.com/p/Coroplast-36-in-x-72-in-x-0-157-in-4mm-White-Corrugated-Twinwall-Plastic-Sheet-COR-3672/202771364

**Comment by DiegoDom23** [comment]
@adamhamdan8 If we go with the uncolored ones we will have to buy the spray paint to paint them, but the plastic sheets seem reasonable and there are some available for pickup. We will talk about it tomorrow to plan it out including when it should all be ready by but I think with the previous materials listed and those sheets I should be able to build them. I do need some guidance on how to bend the sheets into the shape we need, but other than that the process should be very simple.

**Comment by adamhamdan8** [comment]
I purchased white corrugated plastic, spray paint, and zip ties for you guys. I will bring them in tonight at some point, so you guys can start working on them tomorrow! Thanks for the hard work, lets get these done for Sunday.

**Comment by bcobo04** [comment]
The buoy structures for 6 of them are made and are only awaiting spray paint. Both me and @DiegoDom23 are unable to go into the lab tmrw to spray paint them before Sunday. @adamhamdan8 is there anyone who would be able to paint them between now and Sunday so they are given a chance to dry before being put in the water?

**Comment by bcobo04** [comment]
![image](https://github.com/user-attachments/assets/c41a956c-9562-47bb-9320-9a8faa1cacbd)

**Comment by adamhamdan8** [comment]
> water?

Yeah @RyanHoburg and I might just go do it tonight or tomorrow we will handle it! Thank you guys for the hard work.

**Comment by DiegoDom23** [comment]
Buoys were completed and used at this week's NaviGator test. All 6 were deployed and were able to float
