### ISSUE TITLE
Thruster repair

### ISSUE THREAD

**Issue by amcaleer271** [uf-mil-mechanical/tasks#7]
NaviGator has 4 thrusters at the end of long poles. The current mounting system is not very secure, and for some thrusters allow them to rotate. Several repairs and upgrades need to be made, including:

- Stop the thrusters from rotating in their mounts
- Make the mounts more secure
- Add a lever to make it easier to lift/lower the thruster

**Comment by space-cat-explorer** [comment]
We created a design for a mount that would rest in gaps on the current mount and put the draft in fusion. We still need some measurements so we can get a prototype printed.

**Comment by csachs32** [comment]
We measured the dimensions of the gaps and created a design that we think will prevent the thrusters from rotating. We sent the design to the print queue to print a prototype.

**Comment by adamhamdan8** [comment]
@space-cat-explorer @csachs32 Whenever you guys get a chance, put images of measurements, models, etc so that we can refer to it later and so that I can check on things as you're progressing. Great work tho!

**Comment by space-cat-explorer** [comment]
![Thruster Mount assembly](https://github.com/user-attachments/assets/bf7b2ae2-b077-4d72-a5f0-332c837a06d1)

**Comment by csachs32** [comment]
![Image](https://github.com/user-attachments/assets/10e2ec7a-4f70-42cf-8e51-c9f6cedfab88)
Here are the measurements that we took for the part.

**Comment by space-cat-explorer** [comment]
Created a second prototype and sent it to the print que. The parts are: 
Tube Clamp Auto Deploy 2
Tube Clamp Auto Deploy Flat 2
Anti Twist Assembly 2

We decreased the width of the slots and added a little bit of space between them (see pictures below)

**Comment by space-cat-explorer** [comment]
![image](https://github.com/user-attachments/assets/177b015a-fbdb-4af1-b4b9-01c8941ad00c)

**Comment by csachs32** [comment]
Printed the above-mentioned parts, and will test its mounting capabilities tomorrow.

**Comment by csachs32** [comment]
The final prototype works, and we are currently sending the final prints to be printed. They will be made out of PLA with 100% infill.

**Comment by adamhamdan8** [comment]
First print was done, I think PETG instead of PLA. Let me know if you guys need help being let into CIMAR!

**Comment by space-cat-explorer** [comment]
Started with final prints, just waiting on more filament to come in.

**Comment by space-cat-explorer** [comment]
Still need to complete these prints - they were added to the print que but they each take 11 hours so it just depends on when there is availability to print.

**Comment by adamhamdan8** [comment]
We have those in the queue, we just have tons of stuff in the queue now. Don't worry about this issue, I will let you guys know when its printing!

**Comment by space-cat-explorer** [comment]
Cut blocks out of 2x4s for anti-twist on thrusters, took off the back left thruster to install and found that two of the holes have messed up threads. Will require either cleaning or retapping, so I am going to look into getting a t-handle for a tap and the correct size for the tap. Will figure that out on Monday, add stuff to the order form, and try to get it done by the next testing session because I will be gone next weekend (including Friday).

**Comment by adamhamdan8** [comment]
@space-cat-explorer Have you and Gabe had a chance to go into the DML lab? Or are you going today? Also I noticed that the 3D printed part had sheared off, what's the plan for fixing that? Just going back to the original system?

**Comment by space-cat-explorer** [comment]
We are no longer using the 3D printed parts since they would need to be made out of metal to work, and we don't have time to implement them because it would require using both a CNC and water jet machines (neither of which I am allowed to use since I haven't taken DML). So, we added two wood blocks on either side of the existing wood blocks attached to the thrusters to prevent rotation. We allowed a degree or two of rotation so it wouldn't be hard to put the thrusters down in the water. However, we ran into a lot of problems with the threads and hole alignment of the metal plate that the thrusters attach to the boat from (both on back left and back right thrusters). We were able to reattach them as best we could, but it looks bad and is not a long term solution. If needed, it should work for Sarasota. 
The plan as of last Tuesday (I was out of town all weekend so I haven't been able to check back in) was to add Blake and Gabe to this task to help me make a new metal plate so that we can at least have the holes realigned. We spent a lot of time on Tuesday trying to retap the holes, which pretty much worked, so we can do that for each of them and hopefully make the new metal plates before the competition. I feel really bad that I am having to pull Gabe and Blake for this task since I haven't taken DML (stupid aerospace curriculum), but it would be nice to get a long term solution implemented before competition.

**Comment by space-cat-explorer** [comment]
Plan for the rest of this task: 
- Retap all of the holes that are having issues
- Get aluminum stock for the two new plates 
- Take measurements of holes on the boat mount 
- Use either CNC or water jet to put holes in the new plates that align with the preexisting holes on the boat mount
- Reattach thrusters with new plates and new blocks 
- If time before competition: paint the blocks to seal them (this isn't super necessary bc they were just made out of 2x4 scraps in the lab, and can always be cut again)

**Comment by space-cat-explorer** [comment]
Main problem with back left thruster: threads are super messed up
- If retapping works for back left, then hopefully we won't have to make a whole new plate for this one. 

Main problem with back right thruster: holes are misaligned, making it really hard to secure the plate properly without shearing the bolts really bad. 
- This will likely require making a new plate, but we can try retapping the holes to see if that could possibly work.

**Comment by space-cat-explorer** [comment]
Possible solutions for AFTER the competition: 
- Create original parts out of metal so that we don't have to use the wooden block mounts at all
- Completely retap holes on the boat, including redrilling with a bigger hole, tapping that hole, then using a small insert to bring the thread size back to one compatible with 3/8-16 bolts (similar to image below)
![image](https://github.com/user-attachments/assets/2c6e2cae-684c-4c7e-976b-38ee73219528)

**Comment by adamhamdan8** [comment]
@space-cat-explorer @csachs32 Does this need anything else to be done before the competition or am I good to close the issue?

**Comment by space-cat-explorer** [comment]
I fixed the back left thruster mounts by retapping yesterday, and three out of the four bolts go in fine on the back right. However, the top left hole on the back right thruster is misaligned, which can be fixed by drilling a slightly larger hole on the removable plate. I haven't taken DML so I am not allowed to take it to be water jetted (or whatever machine would do the job). Let me know who could possibly take me to get that done.

**Comment by cbrxyz** [comment]
@space-cat-explorer @csachs32 Unfortunately, the right thruster is sitting lower than the left thruster after testing today. Us software people could not figure out what happened or why it's doing that, but just letting you know! The wood block on the thruster itself that rests between the two blocks on the bumpers is just swinging around when the thruster is fully put down, because it's not high enough to fit between the blocks.

**Comment by space-cat-explorer** [comment]
My guess is the metal clasp at the top was not tightened down all the way. I will look at it tomorrow and see if that is the issue

**Comment by space-cat-explorer** [comment]
It might have gotten loosened when I was messing with them yesterday

**Comment by space-cat-explorer** [comment]
So sorry I forgot to do this last night. We fixed the back left thruster by retapping the holes (yay) and we just have to drill a bigger hole on the back left plate to fix that one. Gabe said he would help me with that sometime before we leave before competition. I am also making the mount for the RF kill system, which I am prioritizing because we need that for competition.

**Comment by adamhamdan8** [comment]
Great thanks @space-cat-explorer ! I will remind Gabe to get that done so that we can close this issue as soon as possible.

**Comment by adamhamdan8** [comment]
Motor controller issue this whole time. Completed over the competition by @space-cat-explorer @nonagaga @amcaleer271 and myself kinda.
